### ISSUE TITLE
Issue - Unable to Log in

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#12]
I tried getting on to production this morning and I was able to log on did the authentication code but  then I got this.

![1](https://cloud.githubusercontent.com/assets/25959809/25861449/a39a51c8-3499-11e7-9e60-f98346181c75.png)

Guy Trimarchi
Los Angeles County

**Comment by monte-williams** [comment]
I tried to get to “Production” using chrome,  it accepts my RACF user id and password, emails me a code,  accepts that code, but then when it finally  looks like it will go to the page, I get Unauthorized

Dave Divelbiss
Fresno County

**Comment by monte-williams** [comment]
I closed the chrome browser, and was going to try to get to the sandbox,  but I accidently chose production again, it said I have ‘access’  [or something like that]. Then when I clicked continue,  I got to the search page weird

Dave Divelbiss
 Fresno County

**Comment by monte-williams** [comment]
Let me re-specify that, I did not close all open chrome pages, I had another chrome page in the background still running but closed the production window

Dave Divelbiss
 Fresno County

**Comment by monte-williams** [comment]
Yeah David, when I was testing Search in Production using Chrome I had the same thing happen several times.

Will Dayton
Yolo County

**Comment by david-sanabria** [comment]
@monte-williams I will speak with the developers, but I am not reading enough detail. We need specific, step-by-step user/system action and response. We also need to know if this issue is repeatable using the user/system steps.

**Comment by david-sanabria** [comment]
@ca-cwds/devops-eng + @ca-cwds/intake-dev : This seems like an issue with the SAF login interaction. When we have more details, we will need to investigate.

**Comment by david-sanabria** [comment]
@michaelsampath Can you please provide an update on this issue?

**Comment by michaelsampath** [comment]
We don't have any issues reported in our last couple of meeting with the counties.
