### ISSUE TITLE
Issue - "Blank Screen" (Internet Explorer)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#13]
After logging in there is nothing but a blank, "white", screen.

Reported by - Rosanna Fierro, Yolo County

**Comment by michaelsampath** [comment]
I have requested Rosanna to give me a call or provide me with her number so that I can call her and assist  her.

**Comment by monte-williams** [comment]
Her number was emailed to you.

**Comment by michaelsampath** [comment]
Rosanna is connected now. I walked her through the process to connect to Sandbox. This issue can be closed.

**Comment by david-sanabria** [comment]
@monte-williams The Infrastructure team is reviewing a possible configuration change to Internet Explorer on all managed (Dedicated) desktops, which will change the "Compatibility Mode" settings so that users do not see this blank page. This issue is a known problem with Internet Explorer.
