### ISSUE TITLE
Log in issue - Butte County (Oroville office)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#15]
I just tried to logo on to production. I was only able to login using chrome. With firefox I get the message unauthorized, as I did last week. IE I get webpage cannot be found HTTP400 after I go through the login in process and hit the go to production (after I use access code). 

Tim Garcia, 
Butte County

**Comment by david-sanabria** [comment]
@monte-williams The infrastructure team is working on pushing out a global change that will modify the "compatibility mode" settings in IE in Dedicated workstations. The user should be able to use IE by manually clicking on this setting in the Internet Options panel. I am passing this issue along to our developers as well.

**Comment by monte-williams** [comment]
I could not get onto Production w/ IE. On Chrome, I received a message that reads, “Unauthorized.” 

Lindsay Ellington
Butte County

**Comment by david-sanabria** [comment]
@monte-williams Regarding L. Ellington, the message may be coming from SAF because her ID has not been granted access to Prod from our application. @jcsimko Can you please work with Monte to make sure that this CW has been invited and configured for login to PROD via SAF?
