### ISSUE TITLE
Issue - INT01 App server filesystem 100% full

### ISSUE THREAD

**Issue by david-sanabria** [ca-cwds/devops#2]
# Overview

1. The INT01 App server was not responding, so was rebooted by @ca-cwds/devops-eng team 
2. After rebooting did not restore service, David checked the server directly and found the root filesystem was 100% capacity.
3. A note was posted to the #devops-engineering channel in slack to inform development teams that the App server was down, but as it was after hours we would wait until the following morning to triage the issue.

# Initial Recommendations

1. The default root filesystem size needs to be be increased from 8GB to 100GB
2. L1 (availability) & L2 (capacity) monitoring need to be setup with alerts sent to DOE team (and service desk when we get one).

**Comment by vinod-taborda** [comment]
Int01 environment was setup with a default file system size and we increased the size to 100GB. Wrote shell scripts and updated cron jobs to run the shell script in cleaning the unused docker images and containers

**Comment by david-sanabria** [comment]
Issue has been resolved by updating the cloud formation scripts to use a larger default size.
