### ISSUE TITLE
INT01 Performance Problems - App Server

### ISSUE THREAD

**Issue by david-sanabria** [ca-cwds/devops#3]
# Overview
The @ca-cwds/intake-dev team reported that the Intake application was not responding as a result of the testing they started doing today. The issue was initially reported by @brunoOSI, and triaged by David Sanabria. The API appeared to be stuck, and the java process was consuming 50% of the CPU resources on the application server.

A couple hours after restarting the services on the INT01 App server, @pemaOSI posted a note to the DOE Slack channel to let us know that their testing was killing the app server (reproducible) after only a short period of testing.

**Comment by pemaOSI** [comment]
it is still happening today

**Comment by david-sanabria** [comment]
Last night, we upgraded the server instance from a "t2.medium" (2CPUx 4GB RAM) to a "m4.xlarge". As noted by @pemaOSI, the issue is still a problem this morning and requires additional, joint investigation with Intake and TPT1 Devs ( @osi-richbach + @david-smith-osi ).

**Comment by david-sanabria** [comment]
I copied the docker logs for the API container to /tmp/docker-intake-20170202-1039.log on the INT01-APP server. There is information going back to the Jan 25. 

The Intake container is not configured to output to STDOUT, so their docker log is empty. Their log is stored inside the container in /log/production.log.

**Comment by david-sanabria** [comment]
## Update
I received an update from the API team:

- The API connection to Elastic Search is not being closed as expected
- Each time the API makes a call to Elastic Search it is opening a new connection
- Once the API reaches the limit on the number of open connections, they are unable to make any new requests, and are hanging.

The resolution to this issue is to make a change to the API so that it closes Elastic Search connections after using them. 

In addition to the information from TPT1, we also did some capacity analysis of the servers in the INT01 environment and found that the CPU and memory (RAM) added last night were not used, and thus it is not necessary to increase out standard server from the t2.medium (2CPU,4GB RAM) to the m4.xlarge (4CPU,16GB RAM). We will leave the servers alone for now and will resize them down once the development teams get their components stable again. This also means that we will not need to modify our server sizes in the PERF and PROD environments.

For now, there is nothing else to do except wait for an update to the API, which we will deploy as soon as it is available and approved to release to INT01 by the dev leads. This issue was added to the TPT1 backlog and can be found in the user story linked below.

https://www.pivotaltracker.com/story/show/138951961

## Next Steps
* Wait for new API component to deploy
* Work to be done by TPT1 development team to fix bug.

**Comment by vinod-taborda** [comment]
Last night,  we upgraded the int01 servers  instances from t2.medium to m4.large, and also expanded the storage space volumes in the int01 environment. The Instances in int01 environment  were stopped for an hour, when these changes took place

**Comment by david-sanabria** [comment]
This issue has been confirmed as resolved. Issue was found to be a bug in the API call to Elastic Search.
