### ISSUE TITLE
API JDBC Errors connecting to DB2 in INT01

### ISSUE THREAD

**Issue by david-sanabria** [ca-cwds/devops#4]
# Overview
The API component is unable to connect to the DB2 database from the INT01 App server. JDBC Errors are seen in the docker log, among other exceptions being noted. It is not clear if the issue is in the network, database, or authentication of the user. This issue started Thursday, Feb 9.

# Action Taken
1. Logs have been reviewed
2. Email sent to DB2 DBA requesting troubleshooting assistance.

**Comment by michaelsampath** [comment]
We have established a VPN connection to the DB2 Database and bypassing SSH tunnel. We tested the connectivity and it works.

**Comment by david-sanabria** [comment]
Issue was resolved.
