### ISSUE TITLE
Unable to log in - SAF Screen

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#6]
## Issue Description
Unable to log into R1 Production site due to apparent issue with logging into CWDS SAF first.

## Business Impact
Unable to log into R1 Production site due to apparent issue with logging into CWDS SAF first.

## Date/Time of first occurrence
2017-03-17 08:00

## Is the Issue Repeatable?
[Possible Answers: "Always", "Sometimes", "No"]

**Comment by david-sanabria** [comment]
After reviewing the server logs, we can see that there are users who are able to login and execute searches. The issue is still being investigated.

**Comment by david-sanabria** [comment]
This issue does not appear to be rooted in the application or within the web.cwds.ca.gov environment. Users are recommended to try the following actions:

* Clear Browser Cache
* Confirm RACF ID is active (not locked or expired)

Some users are not able to connect at all, which appears to be a different issue related to the county connectivity through CDT. This issue will be directed to CDT as an incident.

**Comment by david-sanabria** [comment]
Clearing the browser cache appears to be effective for clearing the connectivity issues being reported by non-dedicated counties (service restored). The connectivity issue for dedicated counties is a separate issue and will need to be addressed separately in a new ticket.

**Comment by david-sanabria** [comment]
Confirmed that this issue is resolved for co-located counties. A bug was opened for TPT1 related to the browser cache issue to see if there is anything they can do to mitigate this issue (https://www.pivotaltracker.com/story/show/142082721).

**Comment by monte-williams** [comment]
I am waiting responses.
