### ISSUE TITLE
Connection issue for Butte and Yolo to Production

### ISSUE THREAD

**Issue by chadbratton** [ca-cwds/devops#7]
There is currently an issue with Butte and Yolo being able to do a callback into our production environment. 

Testing is in progress with the DevOps and network team with our test machine being whitelisted on the CDT side the week of March 27th.   The whitelisted machine will simulate a connection from Butte or Yolo so that the specific issue can be tested and resolved as quickly as possible.

**Comment by michaelsampath** [comment]
1. We tested with both proxy on and as well as without the proxy settings on our test machines. CWDS application works without the proxy but fails with proxy. 

2. Counties reported that the application works both on Firefox and Google Chrome and not on IE.

Currently my RACF ID is not authenticating through SAF and we are waiting for CDSS to fix the issue. We will resume our testing by next week when my RACF ID issue gets resolved.

**Comment by michaelsampath** [comment]
All core counties are connected to both production and sandbox, except Chico office at Butte (Butte has two offices, Oroville and Chico) . Chico is able to connect to production and not sandbox. We will have an update by tomorrow, 05/05.

**Comment by michaelsampath** [comment]
Chico is now able to connect to Sandbox. This issue can be reviewed for closure.

**Comment by michaelsampath** [comment]
I was in county connectivity meeting with Wendy and Monte this morning, 05/09,  and nobody reported any issues with connectivity. All Core counties are connected and reported that they are able to access production and sandbox.

**Comment by david-sanabria** [comment]
Issue `resolved`
